Microsoft Windows [Version 10.0.19042.985]
(c) Microsoft Corporation. All rights reserved.

C:\Users\academy>cd C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\Scripts

C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\Scripts>activate

(djangopy_env) C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\Scripts>cd C:\myreprsotari\Python\Django_projects

(djangopy_env) C:\myreprsotari\Python\Django_projects>django-admin startproject dojo_ninja

(djangopy_env) C:\myreprsotari\Python\Django_projects>python manage.py startapp dojo_app
C:\Users\academy\AppData\Local\Programs\Python\Python39\python.exe: can't open file 'C:\myreprsotari\Python\Django_projects\manage.py': [Errno 2] No such file or directory

(djangopy_env) C:\myreprsotari\Python\Django_projects>cd dojo_ninja

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py startapp dojo_app

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py migrate
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python  manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py migrate
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigration
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigration
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py runserver
Watching for file changes with StatReloader
Exception in thread django-main-thread:
Traceback (most recent call last):
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\commands\runserver.py", line 110, in inner_run
    autoreload.raise_last_exception()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\utils\autoreload.py", line 87, in raise_last_exception
    raise _exception[1]
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    autoreload.check_errors(django.setup)()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\utils\autoreload.py", line 64, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>
(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>
(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>
(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>
(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigration
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 91, in populate
    app_config = AppConfig.create(entry)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 224, in create
    import_module(entry)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 972, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dojo_appdjango'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
Traceback (most recent call last):
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 22, in <module>
    main()
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\core\management\__init__.py", line 395, in execute
    django.setup()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\registry.py", line 114, in populate
    app_config.import_models()
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\apps\config.py", line 301, in import_models
    self.models_module = import_module(models_module_name)
  File "C:\Users\academy\AppData\Local\Programs\Python\Python39\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 855, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "C:\myreprsotari\Python\Django_projects\dojo_ninja\dojo_app\models.py", line 3, in <module>
    class dojo(models.model):
AttributeError: module 'django.db.models' has no attribute 'model'

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
Migrations for 'dojo_app':
  dojo_app\migrations\0001_initial.py
    - Create model dojo
    - Create model ninjas

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_app, sessions
Running migrations:
  Applying contenttypes.0001_initial... OK
  Applying auth.0001_initial... OK
  Applying admin.0001_initial... OK
  Applying admin.0002_logentry_remove_auto_add... OK
  Applying admin.0003_logentry_add_action_flag_choices... OK
  Applying contenttypes.0002_remove_content_type_name... OK
  Applying auth.0002_alter_permission_name_max_length... OK
  Applying auth.0003_alter_user_email_max_length... OK
  Applying auth.0004_alter_user_username_opts... OK
  Applying auth.0005_alter_user_last_login_null... OK
  Applying auth.0006_require_contenttypes_0002... OK
  Applying auth.0007_alter_validators_add_error_messages... OK
  Applying auth.0008_alter_user_username_max_length... OK
  Applying auth.0009_alter_user_last_name_max_length... OK
  Applying auth.0010_alter_group_name_max_length... OK
  Applying auth.0011_update_proxy_permissions... OK
  Applying auth.0012_alter_user_first_name_max_length... OK
  Applying dojo_app.0001_initial... OK
  Applying sessions.0001_initial... OK

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from dojo_app.models import *
>>> dojo.objects.create(name='rainman' , name='ghaith', name='aws')
  File "<console>", line 1
SyntaxError: keyword argument repeated: name
>>> dojo.objects.create(name ="rainman" ,city="nablus" ,state ="pas")
<dojo: dojo object (1)>
>>> dojo.objects.create(name="aws" , city="tulkarm" ,state ="pas")
<dojo: dojo object (2)>
>>> dojo.objects.create(name="fadi" ,city="jenin" ,state ="pas")
<dojo: dojo object (3)>
>>> c=dojo.objects.get(id=1)
>>> c.delete()
(1, {'dojo_app.dojo': 1})
>>> dojo.objects.all()
<QuerySet [<dojo: dojo object (2)>, <dojo: dojo object (3)>]>
>>> c=dojo.objects.get(id=2)
>>> c.delete()
(1, {'dojo_app.dojo': 1})
>>> c=dojo.objects.get(id=3)
>>> c.delete()
(1, {'dojo_app.dojo': 1})
>>> dojo.objects.create(name=ghaith , city='nablus' , state='pal')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'ghaith' is not defined
>>> dojo.objects.create('name'=ghaith , city='nablus' , state='pal')
  File "<console>", line 1
    dojo.objects.create('name'=ghaith , city='nablus' , state='pal')
                        ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?
>>> dojo.objects.create(name='ghaith' , city='nablus' , state='pal')
<dojo: dojo object (4)>
>>> dojo.objects.create(name='aws' ,city='tulkarim' , state='pal')
<dojo: dojo object (5)>
>>> dojo.objects.create(name='salman' , city='ramallah' ,state='pal')
<dojo: dojo object (6)>
>>> dojo=dojo.objects.get(id=1)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "C:\Users\academy\Desktop\python_stack\django\django_fundamentals\djangopy_env\lib\site-packages\django\db\models\query.py", line 435, in get
    raise self.model.DoesNotExist(
dojo_app.models.dojo.DoesNotExist: dojo matching query does not exist.
>>> this_dojo=dojo.objects.get(id=4)
>>> this_ninja=ninja.objects.create(first_name='sami' ,last_name='das' ,dojo=this_dojo)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'ninja' is not defined
>>>  this_ninja=ninjas.objects.create(first_name='sami' ,last_name='das' ,dojo=this_dojo)
  File "<console>", line 1
    this_ninja=ninjas.objects.create(first_name='sami' ,last_name='das' ,dojo=this_dojo)
IndentationError: unexpected indent
>>> this_ninja=ninjas.objects.create(first_name='sami' ,last_name='das' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='samaara' ,last_name='abduak' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='fadi' ,last_name='da' ,dojo=this_dojo)
>>> this_dojo=dojo.objects.get(id=5)
>>> this_ninja=ninja.objects.create(first_name='ramiz' ,last_name='das' ,dojo=this_dojo)
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'ninja' is not defined
>>> this_ninja=ninjas.objects.create(first_name='sami' ,last_name='das' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='tamir' ,last_name='das' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='dani' ,last_name='das' ,dojo=this_dojo)
>>> this_dojo=dojo.objects.get(id=6)
>>> this_ninja=ninjas.objects.create(first_name='rami' ,last_name='das' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='karim' ,last_name='das' ,dojo=this_dojo)
>>> this_ninja=ninjas.objects.create(first_name='raq' ,last_name='das' ,dojo=this_dojo)
>>> dojo.objects.value().first()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
AttributeError: 'Manager' object has no attribute 'value'
>>> dojo.objects.first()
<dojo: dojo object (4)>
>>> dojo.objects.values().first()
{'id': 4, 'name': 'ghaith', 'city': 'nablus', 'state': 'pal'}
>>> dojo.objects.values().last()
{'id': 6, 'name': 'salman', 'city': 'ramallah', 'state': 'pal'}
>>> dojo.objects.all().values()
<QuerySet [{'id': 4, 'name': 'ghaith', 'city': 'nablus', 'state': 'pal'}, {'id': 5, 'name': 'aws', 'city': 'tulkarim', 'state': 'pal'}, {'id': 6, 'name': 'salman', 'city': 'ramallah', 'state': 'pal'}]>
>>> ninjas.objects.values().last()
{'id': 9, 'first_name': 'raq', 'dojo_id': 6, 'last_name': 'das'}
>>> exit
Use exit() or Ctrl-Z plus Return to exit
>>> exit()

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
You are trying to add a non-nullable field 'desc' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 2

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
You are trying to add a non-nullable field 'desc' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> dojo.objects.create(name="ras",city='dsk' ,state='fdf')
Invalid input: name 'dojo' is not defined
>>>  dojo.objects.create(name='rav',city='dsk' ,state='fdf')
Invalid input: name 'dojo' is not defined
>>> exit()

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
You are trying to add a non-nullable field 'desc' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> exit()

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
You are trying to add a non-nullable field 'desc' to dojo without a default; we can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows with a null value for this column)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g. timezone.now
Type 'exit' to exit this prompt
>>> exit()

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py makemigrations
Migrations for 'dojo_app':
  dojo_app\migrations\0002_dojo_desc.py
    - Add field desc to dojo

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, dojo_app, sessions
Running migrations:
  Applying dojo_app.0002_dojo_desc... OK

(djangopy_env) C:\myreprsotari\Python\Django_projects\dojo_ninja>python manage.py shell
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> dojo.objects.create(name='dssa' , city='nav' ,state='dsds')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'dojo' is not defined
>>> from dojo_app import *
>>> dojo.objects.create(name='dssa' , city='nav' ,state='dsds')
Traceback (most recent call last):
  File "<console>", line 1, in <module>
NameError: name 'dojo' is not defined
>>> from dojo_app.models import *
>>> dojo.objects.create(name='dssa' , city='nav' ,state='dsds')
<dojo: dojo object (7)>
>>>